//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiarioDigital
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Comentarios
    {
        public int Idcoment { get; set; }
        [Required]
        public string comentario { get; set; }
        public System.DateTime DateComent { get; set; }
        public Nullable<int> postID { get; set; }
        public Nullable<int> userID { get; set; }
    
        public virtual Articulo Articulo { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
