//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiarioDigital
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subcomentarios
    {
        public int IdSubcoment { get; set; }
        public string subComentario { get; set; }
        public Nullable<System.DateTime> fechaSub { get; set; }
        public int ComID { get; set; }
        public int UserID { get; set; }
    
        public virtual Comentarios Comentarios { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
